module.exports = {
  projects: [
    '<rootDir>/apps/admin-portal',
    '<rootDir>/apps/api',
    '<rootDir>/libs/api-interfaces',
    '<rootDir>/libs/profile/feature-search',
    '<rootDir>/libs/profile/data-access',
    '<rootDir>/libs/shared/ui-layout',
    '<rootDir>/libs/api/user-profile',
    '<rootDir>/libs/profile/ui-search',
    '<rootDir>/libs/profile/domain',
    '<rootDir>/libs/shared/ui-spinner',
    '<rootDir>/libs/shared/util-math',
    '<rootDir>/libs/shared/util-error',
    '<rootDir>/libs/shared/ui-error',
    '<rootDir>/libs/profile/feature-shell',
    '<rootDir>/libs/auth/feature-login',
    '<rootDir>/libs/feature-shell',
    '<rootDir>/libs/auth/feature-shell',
    '<rootDir>/libs/auth/util-jwt',
    '<rootDir>/libs/shared/feature-header',
    '<rootDir>/libs/shared/feature-versioning',
    '<rootDir>/libs/profile/feature-details',
    '<rootDir>/libs/profile/feature-details-shell',
    '<rootDir>/libs/profile/ui-player',
    '<rootDir>/libs/fuel/ui-summary',
  ],
};
